name = "TITFL"
license = "MIT"
licenselink = "https://github.com/chrisjake/titfl/LICENSE"
description = "Theme for Hugo and LITFL"
homepage = "https://github.com/chrisjake/titfl"
tags = ["responsive", "clean", "documentation", "docs", "flexbox", "search", "mobile", "disqus"]
features = []
min_version = "0.65"

[author]
  name = "Jake Barlow"
  homepage = "https://github.com/chrisjake/"
